# Site settings
title: Linea
email: your-email@domain.com
description: > 
  In me the tiger sniffs the rose.       
baseurl: "" 
url: "http://LLLinea.github.io"
github_username:  Linea

# Build settings
markdown: kramdown
